Hack for undeclared pthread_yield() on RHEL4.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3103,8 +3103,8 @@ fi
 echo $ECHO_N "checking if pthread_yield needs __USE_GNU defined... $ECHO_C" >&6
   cat >conftest.$ac_ext <<_ACEOF
 
-    #include <ptread.h>
-    main(void) { pthread_yield(); }
+    #include <pthread.h>
+    int main(void) { pthread_yield(); }
 
 _ACEOF
 rm -f conftest.$ac_objext
@@ -3139,6 +3139,58 @@ sed 's/^/| /' conftest.$ac_ext >&5
       echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
       CPPFLAGS="$CPPFLAGS -D__USE_GNU"
+
+
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+  echo "$as_me:$LINENO: checking if pthread_yield needs to be declared" >&5
+echo $ECHO_N "checking if pthread_yield needs to be declared... $ECHO_C" >&6
+  cat >conftest.$ac_ext <<_ACEOF
+
+    #ifdef __USE_GNU
+    # undef __USE_GNU
+    #endif
+    #define __USE_GNU 1
+    #include <pthread.h>
+    int main(void) { pthread_yield(); }
+
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+      echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define NEED_PTHREAD_YIELD_DECL 1
+_ACEOF
+
 
 
 fi
